name: Update awesome list

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          fetch-depth: 0
          lfs: true
      - name: Awesome generator
        uses: simonecorsi/mawesome@latest
        with:
          api-token: ${{secrets.GITHUB_TOKEN}}
          github-email: ${{secrets.USER_EMAIL}}
          github-name: LOsioChico
          output-filename: testing.md
