name: GitHub metrics
on:
  schedule:
    # Runs at 12am UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  # The job below generates the images displayed on lowlighter/lowlighter
  # You can reuse these steps if you want to have a profile page similar to mine.

  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          base: 'header, activity, repositories'
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_traffic: yes
          plugin_languages: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_gists: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15
          config_timezone: America/Bogota
          config_padding: 10%
